name: Release CI
on: 
  push:
  workflow_dispatch:
jobs:
  x64_build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Verify msbuild version
      run: msbuild -version

    - name: Run msbuild
      run: msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v142

    - name: Get current time
      uses: josStorer/get-current-time@v2.1.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/x64/Release/TrafficMonitor.exe
          Bin/x64/Release/*.dll

    - name: Upload pdb files
      uses: actions/upload-artifact@v4.3.3
      with:
        name: x64_${{ steps.current-time.outputs.formattedTime }}_pdb
        path: Bin/x64/Release/*.pdb

  x86_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.7

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Verify msbuild version
      run: msbuild -version

    - name: Run msbuild
      run: msbuild /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v142

    - name: Get current time
      uses: josStorer/get-current-time@v2.1.2
      id: current-time
      with:
        format: YYYYMMDD_HHmmss
        utcOffset: "+08:00"

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: x86_${{ steps.current-time.outputs.formattedTime }}_TrafficMonitor
        path: |
          Bin/Release/TrafficMonitor.exe
          Bin/Release/*.dll

    - name: Upload pdb files
      uses: actions/upload-artifact@v4.3.3
      with:
        name: x86_${{ steps.current-time.outputs.formattedTime }}_pdb
        path: Bin/Release/*.pdb
